1. Create len(10) integer array filled with zeros

In [2]:
import numpy as np
from numpy import random

a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Create 3x5 floating point array filled with ones

In [4]:
b = np.ones((3,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. Create 3x5 array filled with 3.14

In [27]:
c = np.full((3,5),3.14)
c

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

4. Create an array filled with a linear space starting at 0, ending at 20, stepping by 2

In [30]:
x = np.arange(21)[0:21:2]
#x= np.arange(0,21,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

5. Create an array of five values evenly spaced between 0 and 1

In [11]:
y = np.linspace(0,1,5)
y

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 3x3 array of uniformly distributed random (0, 1)

In [4]:
B = np.random.uniform(0,1,(3,3))
B

array([[0.80931707, 0.33373261, 0.57095976],
       [0.8672482 , 0.30133015, 0.62747153],
       [0.11678682, 0.214497  , 0.44184102]])

7. Create a 3x3 array of with mean 0 and standard deviation 1

In [13]:
A = np.random.randn(3,3)
A

array([[ 0.58918485,  0.49263002,  0.03743206],
       [ 1.09942597, -0.8570405 , -0.4192861 ],
       [-0.10860701, -0.08238833, -0.85316184]])

8. Create a 3x3 array of random integers in the interval [0, 10]

In [25]:
C = np.random.randint(0,10,(3,3))
C

array([[3, 6, 7],
       [3, 6, 4],
       [7, 1, 7]])

9. Create a 3x3 identity matrix

In [6]:
z = np.zeros(4)
z.shape=(2,2)
z

array([[0., 0.],
       [0., 0.]])